### PR TITLE
Adds automated link checking and fixes broken links

### PR DESCRIPTION
**Pull request by vishnuravi**
# Adds automated link checking and fixes broken links

## :recycle: Current situation & Problem
This PR adds automated link checking of all markdown files and fixes broken links. The check will run on all pull requests and automatically on the first of each month at midnight.

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — CHANGES_REQUESTED** [review]
Thank you for the fix @vishnuravi! Can we use the chance to directly add the URL link check to this PR. 

I would suggest that we add this for every PR and in addition maybe as automated checks that run every month, e.g., on the first of the month?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by vishnuravi** [comment]
> Thank you for the fix @vishnuravi! Can we use the chance to directly add the URL link check to this PR.
> 
> I would suggest that we add this for every PR and in addition maybe as automated checks that run every month, e.g., on the first of the month?
> 
> https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

Thanks for the feedback @PSchmiedmayer. Markdown link checks have been added here, automated checks have been added on the first of every month, and the PR has been updated to reflect that. This PR requires https://github.com/StanfordSpezi/.github/pull/40 to be merged first, since I have created a new `markdown-link-check` in this organization, rather than use the one from @StanfordBDHG directly to be consistent with how the REUSE and SwiftLint checks are implemented.

**Comment by PSchmiedmayer** [comment]
Added some comments over in the other PR. Thanks for improving this here! 🚀

**Review by PSchmiedmayer — APPROVED** [review]
Thank you @vishnuravi; looks great!

**Pull request merged**
